### ISSUE TITLE
WebUI slows down and/or becomes unreachable when many torrents are active/queued

### ISSUE THREAD

**Issue by antonkvm** [linuxserver/docker-qbittorrent#175] opened 2022-05-26 23:53 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

WebUI should remain as responsive after adding many (~75) torrents as it is with only a handful (~5).

## Current Behavior

WebUI slows down considerably in all facets when many torrents are added:
- After opening WebUI, the list stays empty for at least several seconds before populating with the torrents.
- After clicking a torrent, the info section below takes at least 5 to 10 seconds to update.
- Requesting the WebUI in the browser may take very long, sometimes the request even times out.
- Opening settings or viewing stats takes several seconds at least.
- WebUI sometimes becomes unreachable.

The issue seems to only affect the WebUI, downloads appear to continue as normal.

## Steps to Reproduce

1. Create qBittorrent container with docker-compose.
2. Add a large number of torrents (~75).

## Environment
**OS:** Raspberry Pi OS 32 Bit Buster
**CPU architecture:** armhf/arm32v7
**How docker service was installed:** via Dockerhub
**Hardware:** Raspberry Pi 4B 4GBRAM, external Toshiba 2TB HDD as download destintion

## Command used to create docker container (run/create/compose/screenshot)

Via docker-compose:
```
version: '3.4'
services:
  vpn:
    container_name: vpn
    devices:
      - /dev/net/tun
    dns: 1.1.1.1
    environment:
      FIREWALL: ''
    volumes:
      - /home/pi/docker/openvpn:/vpn
    image: dperson/openvpn-client
    restart: unless-stopped
    cap_add:
      - net_admin
    networks:
      - default
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on: 
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8081
    volumes:
      - /home/pi/docker/qbittorrent_linuxserver:/config
      - /mnt/Toshiba2TB/downloads:/downloads
      - /mnt/Toshiba2TB/moviesAndStuff:/moviesAndStuff
    restart: unless-stopped
networks:
  default:
```

## Docker logs

```
chown: changing ownership of '/downloads/copyrighted material.mkv': Operation not permitted
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8081
```

**Comment by antonkvm** [comment] 2022-05-28 21:17
Upon further reading, I think it might have something to do with my disk cache settings. My download path is on an eternal HDD connected via USB, my config files are on the boot SD card of the Raspberry Pi. I am not very knowledgeable on this topic, if anyone has a suggestion it would be greatly appreciated.

<img width="710" alt="Bildschirmfoto 2022-05-28 um 23 13 57" src="https://user-images.githubusercontent.com/52636743/170843031-aa419e48-2aab-4a2b-965f-2c83c6c2400f.png">

**Comment by antonkvm** [comment] 2022-05-28 21:46
Changing the location of a torrent through 'right clicking' -> 'set location' also results in the web UI becoming unreachable for the duration of the copying process. After the file copying is done, the web UI returns to being reachable and the files at the old location are removed.

**Comment by kovacsgergely83** [comment] 2022-06-02 13:26
Similar issue here (running latest 4.4.3.1-r1-ls199 in Container Station on a QNAP TS431 P2 NAS upgraded to 8GB RAM) since many month now but for me it's not the number of torrents added to qbittorrent but whenever I start a high speed download (~50MByte/s) seem to cause the web UI to become totally unresponsive (it even times out when I try to force reload the webpage). On NAS and Container Station level I can see that almost 2/3 of the CPU and Memory is free when the webUI hangs. I can however easily run 3-4 torrents simultaneously if they are not that getting downloaded at that high speed.

- I already moved my qbittorrent config data to different array than where my downloads are being written to, still no luck. 
- If I try to copy a huge file on my intrenal wired network from my laptop to the NAS I can do that with 1Gbps easily to the same disk, where my downloads are going, and the webUI does not become unresponsive (so it seems like it's not the not the disks/NAS itself being the bottleneck)
- Also I can open any webpages without issues when the WebUI is unresponsive (so I'd say its also not my router getting overloaded).

**Comment by pravardhanreddy** [comment] 2022-06-15 10:24
I am facing the same issue. I have the container running on Ubuntu with 12600k and still the Web UI becomes unresponsive frequently. The only way to fix it is by restarting the container. Its very annoying. I don't know what the problem is

**Comment by MagganaaowK** [comment] 2022-06-21 21:08
Same issue here, used to work really good a couple months ago (sorry can't remember version)

Webui becomes unresponsive whenever i add a torrent and it starts downloading, have to wait until its finished and then ui becomes responsive again

running similar setup to [antonkvm]

**Comment by Skrivoo** [comment] 2022-07-12 20:25
Having the same issue. If I start to download something big the UI stopped responding and if I refresh the page the download starts again from the beginning. Running more than 300 torrents at the same time but same happens if I stop every each of them. After refresh the UI the settings are set to default. I also tried to wait until the download finishes with closed UI but again, download started over when I reopened the UI. This issue I have for a long time, but only frustrating when I wanna download something big, small stuff doesn't always reproduce it. Limiting the speed didn't work either, big files kills me.
My setup: rPi 4B 8GB, 6TB external HDD via USB 3.0, docker is installed on HDD. qBittorrent 4.3.9

**Comment by j0nnymoe** [comment] 2022-07-12 20:52
Like I've said in previous comments, there will be bottlenecks with how your system is setup that is causing the stuff to not respond. Likely the face you're running everything from the same USB external HDD is not going to help. You need to investigate your systems performance to see where the bottleneck is. 

Closing this issue as this is not a container issue, more host configuration setup.

**Closed by j0nnymoe** 2022-07-12 20:52 UTC

**Comment by kovacsgergely83** [comment] 2022-11-10 18:21
I'm happy to report that swithcing to a release that contains **libtorrent v1** instead of v2 significantly increased the responsiveness of the web UI when downloading large files (70GB) at high speed (70-100 MByte/sec) in my case. The exact release I'm using now is: **libtorrentv1-release-4.4.5_v1.2.18-ls2**

(P.S.: be aware that "standard" releases "4.4.5-r2-ls226" and "4.4.5-r2-ls227" also state they have libtorrent v1, but in fact they still have libtorrent v2 inside - you can check this on the "Software Used" tab of the "About" window)

**Comment by blumoreno** [comment] 2024-07-20 02:35
My WebUI becomes unresponsive as well until I restart the container. I am using Gluetun. I noticed the container often will use all available memory (16 GB) as well. Running on an Ubuntu Server 24.04 LTS LXE in Proxmox. The Downloads are mounted via cifs in the fstab.
