### ISSUE TITLE
QBittorrent stuck at downloading metadata

### ISSUE THREAD

**Issue by MacGyver27** [linuxserver/docker-qbittorrent#45] opened 2019-04-09 14:43 UTC
Hey,

When adding new magnet torrents via webui they get stuck in "downloading metadata"..  Sometimes they eventually recovers.. in minutes , hours or days. However sometimes they don't.
Thought it could be my local DNS resolution server on host, but no. Logs don't say much as well.
Anyway port 6881 is allowed on host.

BTW on the same LAN using qb on win and no issues whatsoever.. same magnet starts immediately at full speed.

Host: Debian Buster
Image: latest

Docker-Compose:
```
version: "3.7"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent.528
    restart: always
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 52880:52880
    volumes:
      - $PWD/config:/config
      - /lvm/raid/private/media/.downloads:/downloads
    environment:
      - TZ=Europe/Prague
      - PUID=1000
      - PGID=994
      - UMASK_SET=022
      - WEBUI_PORT=52880
    labels:
      - traefik.enable=true
      - traefik.port=52880
      - traefik.frontend.entryPoints=https
      - traefik.frontend.rule=Host:qb.example.com
      - traefik.backend=qbittorrent.528
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true

networks:
  default:
    name: qbittorrent.528
```

However googling around found this issue: https://github.com/qbittorrent/qBittorrent/issues/5006#issuecomment-201619521 and it seems to be the case.
Another reddit thread: https://www.reddit.com/r/qBittorrent/comments/7x03yk/stuck_on_downloading_metadata_on_one_pc/
And from linustechtips forum:
![image](https://user-images.githubusercontent.com/6546231/55811307-384d9880-5ae9-11e9-9cd2-df1c8f0b23b4.png)

**So just by changing the port it starts immediately working again. They say this needs to be done on every startup..**

Any ides how to address this for the future? Thanks

**Comment by MacGyver27** [comment] 2019-04-11 11:06
OK, it wont recover by itself.. after 2 days torrent still stuck at **downloading metadata**..

**Comment by Deleetdk** [comment] 2019-04-16 05:30
This issue is revolved by restarting the application. In my case, it won't close properly either, so I force kill it. After restarting, it will download the metadata. After some time, any new torrent will be stuck at the metadata stage again, and so one has to keep restarting it. I don't know any better solution.

**Comment by MacGyver27** [comment] 2019-04-16 09:51
I dont get it.. this is some nonsense.. why host install or windows install is ok but dockerzied no?

**Comment by MacGyver27** [comment] 2019-04-24 08:58
another week.. any conclusion??

**Comment by thelamer** [comment] 2019-07-20 01:43
We ingest this directly from their PPA, I also have not been able to duplicate this. 
Try network bridge mode and pull traefik out from the equation. 
I do apologize for the delay , but we do not officially support windows as a platform and I do not believe there are any changes we can make in order to resolve this bug, we simply install the package provided by upstream in a Docker container. 
I will be closing this issue.

**Closed by thelamer** 2019-07-20 01:43 UTC

**Comment by Daskarzine** [comment] 2019-11-17 22:27
I have the same problem (Mac) anyone find a solution? Doesn't happen with torrents from anywhere else but my favorite EZTV

**Comment by HadiSDev** [comment] 2019-11-18 08:10
I am also having this issue.

**Comment by dmayan-ss** [comment] 2019-11-22 14:12
Same issue here

**Comment by j0nnymoe** [comment] 2019-11-22 15:42
Stop adding unhelpful comments of `Same Issue Here`.

If you wish to report an issue, open a new issue or jump over to our discord.

**Comment by dmayan-ss** [comment] 2019-11-22 16:02
Stop being an asshole. Is THE SAME ISSUE, I won't open a new issue for the same shit. No worries, already dumped this shit for another that worked instantly. Kisses

**Comment by MacGyver27** [comment] 2019-11-22 16:20
> Stop adding unhelpful comments of `Same Issue Here`.
> 
> If you wish to report an issue, open a new issue and fill in the requested details or jump over to our discord.

If I recall correctly issue tracker is for reporting issues.. Discord is mainly for the support - no way other people would be able to track down the solution. So if you are willing to help, address problem here. That's where the google brings users not discord.. 

Anyway I took some time to test it from every corner and provided you with the all data about the case and noone really cared.. thanks.

**Comment by aptalca** [comment] 2019-11-22 17:51
According to the GitHub thread you linked to earlier, it seems to be an upstream issue: https://github.com/qbittorrent/qBittorrent/issues/5006#issuecomment-554902476

But in any case, if there is one report of a potential bug with additional info it is often not enough for us to troubleshoot unless we can reproduce it ourselves.

In such cases, other people jumping on with "same issue" is not helpful unless they also add their specific info that might help us identify a common denominator and perhaps reproduce the issue.

**Comment by Daskarzine** [comment] 2019-11-22 20:59
So is there something we can do to stop the issue from happening and get the torrent started automatically and if more information is required, what is required?

**Comment by Daskarzine** [comment] 2019-12-07 01:15
anyone have a solution or found anything that works?

**Comment by macintoshee** [comment] 2019-12-29 16:13
In may case I have found a reason for that behaviour.
It works as long as I don't use proxy. As soon as I switch over to proxy it stalls (stuck at downloading metadata). Switch off proxy and restart app and it starts to download again.

It first appeared after update to 4.2.1. I tried to downgrade with clean install but without success. 4.1.9 and 4.1.5 acted the same way.  As soon as I switch to proxy it stalls at downloading metadata.

**Comment by ketiil** [comment] 2019-12-30 12:51
Same behaviour as macinoshee, also on 4.2.1. Works when turning off proxy. Also works again when turning proxy on after metadata has been downloaded. 

If I add new magnet links after turning proxy on again, it's stuck at same issue, downloading metadata.

**Comment by macintoshee** [comment] 2019-12-30 13:07
Yes, true. As soon as metadata is downloaded I can switch proxy on and it continues download.

**Comment by ThiagoScala** [comment] 2020-01-14 14:37
I just had this issue. Force Restarting worked for me

**Comment by pomkos** [comment] 2020-01-18 01:12
I can confirm the proxy issue. Add magnet link: stalls at metadata downloading (usually, sometimes it works as normal). Turn off proxy, wait for metadata to download, turn on proxy and it keeps downloads.

This is using docker inside a FreeNAS VM of RancherOS. The proxy used is privateinternetaccess.

**Comment by Downtownlou** [comment] 2020-02-15 19:51
I've been having this issue since like 3.6 or 3.7 on mac OS. I just updated to 4.2 to see if this bug was fixed and was pissed to see it was stalling again. 

I selected "Use different port on each startup" and it the torrents immediately moved from downloading metadata to downloading.

**Comment by Stokestack** [comment] 2020-02-19 21:16
Same problem but not in a docker, and restarting does not fix the problem.

**Comment by spicerackk** [comment] 2020-03-18 06:28
Having this issue on Windows 10 v4.2.1. Restarting Qbit doesn't solve the problem.

**Comment by CameronSokalski** [comment] 2020-03-27 00:08
Having the same issue with proxy on windows 10. also using privateinternetaccess as the proxy. quitting the application and relaunching fixes the issue temporarily

**Comment by methanoid** [comment] 2020-03-27 14:15
> ## Before port modification
> ![image](https://user-images.githubusercontent.com/6546231/55810474-e7897000-5ae7-11e9-9b3d-f51b0509bb3e.png)
> 
> ## Right after port change (not even 10s)
> ![image](https://user-images.githubusercontent.com/6546231/55810508-f7a14f80-5ae7-11e9-86e6-f2d6fcef9a91.png)
> 
> So port change needs to be done **every time new torrent is added** to trigger the download..

Thanks, as a fix that works for me until a proper fix comes along.... I'm using Qbittorrent-VPN docker

**Comment by xaxxon** [comment] 2020-05-12 02:12
Just updating people that this is still a thing in 4.2.5.

**Comment by Thatkookooguy** [comment] 2020-05-14 11:27
@xaxxon yup. just encountered this as well :-(

**Comment by HikariNoKitsune** [comment] 2020-05-17 16:58
Was working fine for me at first. I'm currently running Ubuntu Server 20.04 on physical hardware, not in a docker, nor in a vm.. bare metal.

I am using this in conjunction with Sonarr. 

Sonarr grabs the show, passes the magnet url to qbittorrent, and qbittorrent downloads the show. 

First test worked fine, except that after download, Sonarr could not access the download location... So to possibly fix this, I created a folder in a publically accessible location, and changed permissions so everyone and their grandmother could access it...

After changing the default download directory to this new folder, I've gotten stuck on 'downloading metadata' for EVERY SINGLE thing added... I am NOT using a proxy. But if I enable proxy without giving it any real proxy info, it will go away from the 'metadata' thing, and go into 'downloading' but does nothing. Once I switch back to 'none' for proxy, it then downloads a few bytes of data, then nothing. Still says "downloading" but nothing is actually being downloaded. it can see thousands of seeds and peers, yet nothing. I tried switching back to the default qbittorrent-nox/Download directory, and still nothing happens... 

At this point, the people going "this is an upstream issue" need to actually think about what's going on... because its not an upstream issue at this point... its an issue with the programming, and something is broken, so work obviously needs done to it and people are just not willing to do it... I remember I used to use it on windows as my main torrent downloader, but moved away from it ages ago and couldn't remember why I did, but figured that whatever made me want to move away must have been fixed by now... but if it was fixed, seems this other issue has not been...

**Comment by HikariNoKitsune** [comment] 2020-05-17 17:18
Quick update... in case anyone else needs to know:

Check your rate limits. I **THINK** I figured out what's causing it. If your rate limits for upload are set to 0, then change them to something reasonable. If they are set to under 25KiB/s then set them to AT LEAST 25KiB/s from my testing... 

After doing this, everything immediately started downloading, and all the stalled downloads restarted. I've tested this with 5 different downloading files so far, and every time when I have the upload set to 0 (for unlimited) nothing happens, and when under 25KiB/s nothing happens. But once I set it to 25KiB/s or higher, everything started working again.

Now though, I'm not sure if this is what they're referring to as an 'upstream issue', as I was under the impression that when they kept saying 'upstream issue' they were talking about the code being uploaded to the PPA and thus being what gets 'downloaded' to the community... but now I'm wondering if they are talking about the upload of whatever "we" are trying to download. 

Although, with all this said, I do seem to still have an issue with a single download, as the download speed is unusually slow compared to everything else... suck to around 50-100KiB/s instead of 20MiB/s... I'm not sure if this is just because out of all the files I've tested, this one happens to be the 'newest' as it was just uploaded today... but I feel some more testing is needed..

**Comment by VictoralcNunes** [comment] 2020-05-18 19:09
Hi guys.

I was having the same problem here, but as you commented before about changing ports I looked for on qb and found the option to use a different port every time it initializes and it worked for me!

Hope it was helpful!
![qbit port change](https://user-images.githubusercontent.com/16855513/82250458-e00adc00-9921-11ea-934c-2f659798d40a.JPG)

**Comment by ThiagoScala** [comment] 2020-05-22 17:44
I just got this problem again, and i notice this warning at the bottom of the window. But i click and goes to the Connection Tab but i don't know what to change there.

![image](https://user-images.githubusercontent.com/50633380/82694992-9c261880-9c3a-11ea-93b2-0d10a4e2b183.png)

**Comment by Downtownlou** [comment] 2020-07-10 23:00
does anyone have any new workarounds for this? as @xaxxon pointed out the behavior seems to be the same on 4.2.5. using a different port on startup doesn't work anymore for me.

**Comment by cbartondock** [comment] 2020-07-20 12:35
Exact same issue. Client is bricked as far as I'm concerned, completely unusable.

**Comment by methanoid** [comment] 2020-07-20 12:44
" Client is bricked as far as I'm concerned, completely unusable." -
hardly... that's just unfair. Mine is stable for about a week at a time..
but I have to restart the docker if it hangs. Its annoying but not bricked
or unusable by any means.

**Comment by tycrek** [comment] 2020-07-20 17:53
Just thought I'd add: I'm using qBittorrent-nox 4.2.5 and using Torguard's SOCKS5 proxy. Enabling "Use Random Port on Startup" fixed my issues. Also drastically improved my speeds which is a plus. I did *not* have to adjust my rate limits; they are still set to 0.

**Comment by Stokestack** [comment] 2020-07-20 20:05
This isn't Docker-specific anyway. The client (or the underlying lib) is pretty pathetic. I'm sticking with 4.2.1 and have the "use random" option selected, and eventually it usually works. Sometimes I'll restart it after a download completes if the remaining ones are still "downloading metadata."

**Comment by p060477** [comment] 2020-07-21 19:48
hi!
same issue
vers 4.2.5
win 10 home 64 latest vers 2004
the port random sometimes works and sometimes not at all..
really hope that the qbit dev will fix it..it is so frustrating...
:(

**Comment by cbartondock** [comment] 2020-07-22 09:28
@methanoid I was pointing out the severity of the issue in my case. No torrents download, hence not really usable. I am also on windows 10, not docker.

**Comment by p060477** [comment] 2020-07-22 13:09
> 
> 
> @methanoid I was pointing out the severity of the issue in my case. No torrents download, hence not really usable. I am also on windows 10, not docker.

i totally AGREE with you
the sw now for me is completely UNUSABLE...
win 10 home 64 latest vers 2004
really hope at QBittorrent take care of us and fix this very frustrating BUG

**Comment by j0nnymoe** [comment] 2020-07-22 15:26
Going to lock this issue for now as it's obvious that the problem is upstream. If this does ever get fixed upstream and needs repairing in our container, please open a new issue.
