### ISSUE TITLE
[BUG] 4.5.0 &can't change to Simplified Chinese

### ISSUE THREAD

**Issue by Mrxlei** [linuxserver/docker-qbittorrent#213] opened 2022-12-19 14:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

can't change to Simplified Chinese

### Steps To Reproduce

can't change to Simplified Chinese

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
Have you solved the problem?
```

### Container logs

```bash
…………
```

**Comment by thespad** [comment] 2022-12-19 14:29
Duplicate of https://github.com/linuxserver/docker-qbittorrent/issues/205

**Closed by thespad** 2022-12-19 14:29 UTC
