### ISSUE TITLE
[BUG] laster version set language

### ISSUE THREAD

**Issue by junyuyuan** [linuxserver/docker-qbittorrent#217] opened 2023-01-09 02:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to set the UI display to Simplified Chinese

### Steps To Reproduce

UI display is set to Simplified Chinese

### Environment

```markdown
- OS: DSM 7.1.1-42962 Update 1
- How docker service was installed: 20.10.3-1308
```

### CPU architecture

x86-64

### Docker creation

```bash
Synology Docker linuxserver/qbittorrent
```

### Container logs

```bash
qBittorrent.conf
General\Locale=zh ← wrong result
General\Locale=zh-CN ← correct result
```

**Comment by 568145697** [comment] 2023-01-09 06:03
存在此问题  升级到4.5  至今未解决 unraid  docker安装QB

**Comment by sususu98** [comment] 2023-01-11 09:18
I have the same problem

**Comment by thespad** [comment] 2023-01-11 09:22
Duplicate of https://github.com/linuxserver/docker-qbittorrent/issues/205

**Closed by thespad** 2023-01-11 09:22 UTC
