### ISSUE TITLE
[FEAT] Script post-up

### ISSUE THREAD

**Issue by Jorman** [linuxserver/docker-qbittorrent#253] opened 2023-08-02 21:47 UTC
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi, maybe this is already possible, but I don't found any information about that.

It's possible to include a ENV to point at one external script?
The purpose is to execute a post_up script and if you think is a good idea maybe is also possible to set a new ENV for a pre_up script

### Reason for change

The main reason is, for example, to create a script to catch one external port_forward saved from another container.
This's just one example, there's endless possibility

### Proposed code change

I don't have any code, but just the ENV variable name:
POST_UP_SCRIPT

and if you want to "complete" the range of possibility, you can also add
PRE_UP_SCRIPT

**Comment by thespad** [comment] 2023-08-02 22:43
https://www.linuxserver.io/custom

**Comment by Jorman** [comment] 2023-09-02 21:17
Hi @thespad, thank you for your reply, and sorry for my late reply.
I checked the page you linked, I didn't know these features existed, I think you are referring to the "Private Custom Scripts" section, but if I understand correctly this feature is used before any service is activated.
"Custom Scripts run after built-in and any applied mod init steps but before any services start."
If I am not mistaken, this also means before qbittorrent is started.
Instead, I am looking for a way to start a script after the whole docker has started.

**Comment by thespad** [comment] 2023-09-03 11:36
In which case there are a couple of options - you could use a cron job, or you could you could manually add some s6 init scripts to run after all the services, but that's complicated and requires a good understanding of how s6 works (unlike the custom scripts functionality which we've made as simple as possible to drop in).

**Comment by Jorman** [comment] 2023-09-03 22:13
Cronjob sounds good for me, but I don't know if I can use "at now" for the option
I searched a little bit for docker-compose and I found command: [] option for docker-compose, do you have any idea which one can be better in this case? Maybe do you face some similar problem one time ago.

After a very quick try, seems that after the docker go up and command take place, qBittorrent exit with SIGTERM, I don't know why maybe is a "normal" behavior in the command options for docker-compose, I've to search

**Comment by thespad** [comment] 2023-09-03 22:29
You can't use `command` with the s6 init process as it will supplant the normal init process and only execute the commands you provide.

**Comment by Jorman** [comment] 2023-09-04 13:37
I'm not familiar with S6, I looked for information, and if I understand correctly, it's an overlay that needs to be applied during the build phase right?
When I talked about `command`, I really meant to this, is just an example:
```
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    ...
    command: [ "myscript.sh" ]
```
Maybe it's the same thing you're saying, just to make sure we're talking about the same thing.
In this example of mine `command` works but right after executing the command, the qBittorrent docker crashes with the `SIGTERM` signal and I think it depends on the fact that, as you said, only the command I tell it is executed.

So I'm going to try cron, do you know of any examples of scripts that rely on cron, so I can see and learn what the structure should look like?

**Comment by thespad** [comment] 2023-09-04 14:49
We have a mod that should help https://github.com/linuxserver/docker-mods/tree/universal-cron/

**Comment by Jorman** [comment] 2023-09-10 15:30
Hi, thanks for pointing out the mod, maybe it was already installed, but I don't think it's a problem
```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-cron to container
[mod-init] linuxserver/mods:universal-cron at sha256:5d7d862a06d872793733eafb9574aa6dac483409b631d0d181c71803bedb5f53 has been previously applied skipping
[migrations] started
[migrations] no migrations found
usermod: no changes
```
May I kindly ask if there is any example of usage? I only need to run the script once after qBittorrent has started but I wouldn't know how to do it with cron (I mean a script that only runs once and that's it)
Is there perhaps any documentation on how to use this mod of yours?

Thank you

**Comment by aptalca** [comment] 2023-09-10 15:37
It's all explained in the readme that's linked above.

Closing as it's not a bug. If you need further help, you can seek community support on our discord server in the `#other-support` channel

**Closed by aptalca** 2023-09-10 15:37 UTC
Labels: enhancement
