### ISSUE TITLE
Stuck on the Login page

### ISSUE THREAD

**Issue by MadRajib** [linuxserver/docker-qbittorrent#109] opened 2021-03-01 11:30 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

Stuck on the logging page. The app seems to redirect to the login page if the username and password are correct.

**Comment by Roxedus** [comment] 2021-03-01 12:02
Please provide the missing info

**Comment by retrocats** [comment] 2021-03-02 06:18
Same issue here. Created with docker compose in portainer on raspberry pi. Default login is accepted according to logs but just reloads login page

**Comment by j0nnymoe** [comment] 2021-03-02 06:43
@retrocats your issue is this https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal

**Comment by retrocats** [comment] 2021-03-02 15:28
that did the trick. thanks!

**Comment by josmellop** [comment] 2021-03-02 17:57
In my raspberry neither of the propose solutions worked. Maybe we could get a "bionic" image, like Plex docker? :(

**Comment by Roxedus** [comment] 2021-03-02 18:00
> Maybe we could get a "bionic" image, like Plex docker? :(

Wont happen. We don't want to enable people to stay on outdated OS's

**Comment by josmellop** [comment] 2021-03-02 20:59
Then why in another docker it it maintained? I can't update my raspberry to 64bit OS, and I must stay in an older version of this docker because of it.

**Comment by Roxedus** [comment] 2021-03-02 21:02
Other circumstances. Please jump on to our discord if you need help following the FAQ, don't hijack another thread.

**Comment by j0nnymoe** [comment] 2021-03-02 21:06
> Then why in another docker "bionic" exists? I can't update my raspberry to 64bit OS, and I must stay in an older version of this docker because of it.

Because when we first discovered the problem, they were the only containers that had the issue (and we wasn't aware of the fix) now the issue is actually is with libseccomp2 and not our containers, we provided an faq on how to fix it on specific platforms. Those bionic tags will be dropped soon.

**Comment by j0nnymoe** [comment] 2021-03-02 21:08
Closing issues as original poster hasnt provided enough information but we have assumed the fix is due to the link above. please reopen if the case is different.

**Closed by j0nnymoe** 2021-03-02 21:08 UTC
Labels: invalid
