### ISSUE TITLE
[BUG] <Mouse right click not working>

### ISSUE THREAD

**Issue by L1cardo** [linuxserver/docker-qbittorrent#236] opened 2023-03-23 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mouse right click not working

### Steps To Reproduce

1. right click on the item

### Environment

```markdown
- OS: ubuntu22.04
- How docker service was installed: docker official tutorial
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=qbittorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e WEBUI_PORT=8080 \
  -p 8080:8080 \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -v /path/to/appdata/config:/config \
  -v /path/to/downloads:/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/qbittorrent:latest
```

### Container logs

```bash
[~] # docker logs qbittorrent
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[custom-init] No custom files found, skipping...
WebUI 界面将在内部准备不久后启动。请稍等…
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment] 2023-03-23 18:06
Your volume paths are incorrect, you need to change the `/path/to` parts to something specific to your setup.

**Comment by drizuid** [comment] 2023-03-24 11:24
your PUID and PGID were clearly set later as well, which is why you see 911 in the logs. You need to fix the volumes and recreate the container

**Comment by L1cardo** [comment] 2023-03-24 11:44
Of cource I did put the write path, I just forget to change it above. This is the correct command.
```
docker run -d \
  --name=qbittorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e WEBUI_PORT=8080 \
  -p 8080:8080 \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -v /share/CACHEDEV1_DATA/Appdata/qbittorrent:/config \
  -v /share/CACHEDEV1_DATA/Media:/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/qbittorrent:latest
```

**Comment by j0nnymoe** [comment] 2023-03-24 11:48
Your docker run command and your logs don't match up. Specifically because your logs show PUID/PGID 911, not 1000.

**Comment by L1cardo** [comment] 2023-03-24 11:58
Ok, I reran the container with:
```
docker run -d \
  --name=qbittorrent \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Asia/Shanghai \
  -e WEBUI_PORT=8080 \
  -p 6363:8080 \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -v /share/CACHEDEV1_DATA/Appdata/qbittorrent:/config \
  -v /share/CACHEDEV1_DATA/Media:/downloads \
  --restart always \
  lscr.io/linuxserver/qbittorrent:latest
```

log:
```
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    0
User GID:    0
───────────────────────────────────────
[custom-init] No custom files found, skipping...
WebUI 界面将在内部准备不久后启动。请稍等…
[ls.io-init] done.
```

Right click is still not working, and I don't think a WEB-UI issue is related to PUID/PGID

**Comment by j0nnymoe** [comment] 2023-03-24 11:59
To be honest, I personally think the issue is going to be browser related.
Likely an extension or a bug within qbittorrent itself. Might be wise to ask them direct.

**Comment by drizuid** [comment] 2023-03-24 12:01
We also don't support using a PUID or PGID of 0 on our containers.

**Comment by L1cardo** [comment] 2023-03-24 12:02
@drizuid Come on man, can you just leave that PUID/PGID 😢

**Comment by drizuid** [comment] 2023-03-24 12:16
>  It was fine on the previos version, I updated to 4.5.2, and it became like this.

Hence J0nnymoe's suggestion you contact the qbit devs for THEIR updated release which has apparently broken for you. We maintain the container, not the application.

**Comment by j0nnymoe** [comment] 2023-05-25 22:10
Closing as not an issue with the container.

**Closed by j0nnymoe** 2023-05-25 22:10 UTC
Labels: no-issue-activity
