### ISSUE TITLE
[BUG] Cannot access WebUI with completely new docker image and default settings

### ISSUE THREAD

**Issue by joshoram80** [linuxserver/docker-qbittorrent#305] opened 2024-04-27 05:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempt to access via IP:Port. Get unauthorized

### Expected Behavior

WebUI should load

### Steps To Reproduce

docker compose up -d

### Environment

```markdown
Ubuntu 20.04
Docker install via apt
```

### CPU architecture

x86-64

### Docker creation

```bash
# qBittorrent - Torrent downloader
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    #network_mode: "service:gluetun"
    ports:
      - 8888:8080 # Explosed via gluetun
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - $HTPCDIR/data:/data # Ensure that the downloads folder is set to /data/downloads in qBittorrent
    environment:
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 002
      WEBUI_PORT: 8080
```

### Container logs

```bash
The WebUI administrator username is: admin
27/04/2024
15:19:04
The WebUI administrator password was not set. A temporary password is provided for this session: xxxxxx
27/04/2024
15:19:04
You should set your own password in program preferences.
27/04/2024
15:19:04
Connection to localhost (127.0.0.1) 8080 port [tcp/http-alt] succeeded!
27/04/2024
15:19:04
[ls.io-init] done.
```

**Comment by Aypeus** [comment] 2024-05-13 00:27
Mine has stopped working as well..

```
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    volumes:
      - ./:/config
      - /mnt/nas/media:/downloads
    network_mode: "container:gluetun"
    restart: unless-stopped
```

```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9075:9075/tcp #HTTP Control Server 
      - 8085:8085 # qBittorrent WebUI
      - 6881:6881/tcp # qBittorrent torrenting port
      - 6881:6881/udp # qBittorrent torrenting port
    volumes:
      - ./:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=***************************
      - WIREGUARD_ADDRESSES=***************************/**
      - SERVER_CITIES=***************************
      - TZ=Europe/Stockholm
      - UPDATER_PERIOD=24h
      - HTTP_CONTROL_SERVER_ADDRESS=:9075
      - HTTP_CONTROL_SERVER_LOG=ON
    restart: unless-stopped

**Comment by aptalca** [comment] 2024-05-13 02:18
OP did not do the port mapping correctly. The limitation is explained in the readme.

Second poster's issue is likely gluetun related, which we don't provide support for.

**Comment by Aypeus** [comment] 2024-05-13 07:06
> OP did not do the port mapping correctly. The limitation is explained in the readme.
> 
> Second poster's issue is likely gluetun related, which we don't provide support for.

You are are assuming and you are wrong, cause it has been working without any issues, both services, as I said IT just _from everything working fine_ went to _not working_

so I went ahead and got a older image of qBittorrent and guess what, everything is working.

Assuming shouldn’t be  part of troubleshooting.

**Comment by Roxedus** [comment] 2024-05-13 07:26
No assumptions are made? Aptalca is just setting expectations that we will not support gluetun. 

There are two symptoms here, OPs `unauthorized` (which is to be expected when the information in the readme about the portmapping is not followed), and your `WebUI can not be accessed`.

There is not provided enough information to troubleshoot, as the image works fine in our tests, which are not using gluetun. 

> older image of qBittorrent [...unnecessary hostility..], everything is working

Does not help, what version? some ancient one from years ago? or just 2-3 builds ago?

**Comment by Aypeus** [comment] 2024-05-13 08:23
> No assumptions are made? Aptalca is just setting expectations that we will not support gluetun. 
> 
> 
> 
> There are two symptoms here, OPs `unauthorized` (which is to be expected when the information in the readme about the portmapping is not followed), and your `WebUI can not be accessed`.
> 
> 
> 
> There is not provided enough information to troubleshoot, as the image works fine in our tests, which are not using gluetun. 
> 
> 
> 
> > older image of qBittorrent [...unnecessary hostility..], everything is working
> 
> 
> 
> Does not help, what version? some ancient one from years ago? or just 2-3 builds ago?

I got triggered by that exact fact, there is no need to point out that this team dose not support some other tools, no one is actively or indirectly seeking any support for such situation or issue either..

OP did (and so did) try to run qBittorrent without the dependency of Gluetun. I actually even removed Qluetune and qBittorrent (including Networks) images entirely and restarted the Docker Daemon even. Pulled the latest image of qBittorrent with all new auto generated config files and the problem was exactly the same.

I for one fail to see logical reasons for this issue being related to any other service I'm running so I have not mentioned any of those.

There is no hostility from my part but sure if that is your take of things then that is on you.

We are here reporting the issue encountered, if the logs and so on are not enough then please do point out what else is required.

**Comment by Roxedus** [comment] 2024-05-13 08:30
Would probably need a bit more than the issue template asks for. This should cover enough to troubleshoot further.
https://docs.linuxserver.io/general/how-to-get-support/

**Comment by DarkWayC0de** [comment] 2024-05-28 19:07
hello good afternoon i also have the same fault as described above. 
When I try to access the web interface I get the error “404 page not found” I provide information provided by the command so you can determine the problem.



`Linux openmediavault 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
Docker version 26.1.3, build b72abbb
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
docker run \
  --name "/Qbittorrent" \
  --runtime "runc" \
  --volume "/docker/appdata/qbittorrent2:/config:rw" \
  --volume "/docker/qbittorrent/downloads:/downloads:rw" \
  --log-driver "json-file" \
  --restart "unless-stopped" \
  --publish "0.0.0.0:6881:6881/tcp" \
  --publish "0.0.0.0:6881:6881/udp" \
  --publish "0.0.0.0:8080:8080/tcp" \
  --network "autodownloader_default" \
  --network-alias "Qbittorrent" \
  --network-alias "Qbittorrent" \
  --hostname "d802e3288db2" \
  --expose "6881/tcp" \
  --expose "6881/udp" \
  --expose "8080/tcp" \
  --env "PGID=100" \
  --env "TZ=Europe/London" \
  --env "WEBUI_PORT=8080" \
  --env "TORRENTING_PORT=6881" \
  --env "PUID=1003" \
  --env "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
  --env "PS1=$(whoami)@$(hostname):$(pwd)\\$ " \
  --env "HOME=/config" \
  --env "TERM=xterm" \
  --env "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0" \
  --env "S6_VERBOSITY=1" \
  --env "S6_STAGE2_HOOK=/docker-mods" \
  --env "VIRTUAL_ENV=/lsiopy" \
  --env "LSIO_FIRST_PARTY=true" \
  --env "XDG_CONFIG_HOME=/config" \
  --env "XDG_DATA_HOME=/config" \
  --label "build_version"="Linuxserver.io version:- 4.6.4-r1-ls332 Build-date:- 2024-05-26T13:47:44+00:00" \
  --label "com.docker.compose.config-hash"="5edb1ee8b05964e97a18b838d7b1f5bfcfbd2afbc0c0ffe608ebcbd5a8cabb48" \
  --label "com.docker.compose.container-number"="1" \
  --label "com.docker.compose.depends_on"="" \
  --label "com.docker.compose.image"="sha256:7b68e0d8447d470e38f3fb474f022502c5ce4333931ea8f345a50421562b065d" \
  --label "com.docker.compose.oneoff"="False" \
  --label "com.docker.compose.project"="autodownloader" \
  --label "com.docker.compose.project.config_files"="/root/docker/docker-compose.yaml" \
  --label "com.docker.compose.project.working_dir"="/root/docker/" \
  --label "com.docker.compose.replace"="c007140a1d22fe02669a56fd4ceeffbf18c6cbe75f3d6bd4e7d58f7c69200da4" \
  --label "com.docker.compose.service"="Qbittorrent" \
  --label "com.docker.compose.version"="2.27.0" \
  --label "maintainer"="thespad" \
  --label "org.opencontainers.image.authors"="linuxserver.io" \
  --label "org.opencontainers.image.created"="2024-05-26T13:47:44+00:00" \
  --label "org.opencontainers.image.description"="The [Qbittorrent](https://www.qbittorrent.org/) project aims to provide an open-source software alternative to µTorrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar library." \
  --label "org.opencontainers.image.documentation"="https://docs.linuxserver.io/images/docker-qbittorrent" \
  --label "org.opencontainers.image.licenses"="GPL-3.0-only" \
  --label "org.opencontainers.image.ref.name"="40bba54f1f375b2b5cd7acd328bb818522f6436e" \
  --label "org.opencontainers.image.revision"="40bba54f1f375b2b5cd7acd328bb818522f6436e" \
  --label "org.opencontainers.image.source"="https://github.com/linuxserver/docker-qbittorrent" \
  --label "org.opencontainers.image.title"="Qbittorrent" \
  --label "org.opencontainers.image.url"="https://github.com/linuxserver/docker-qbittorrent/packages" \
  --label "org.opencontainers.image.vendor"="linuxserver.io" \
  --label "org.opencontainers.image.version"="4.6.4-r1-ls332" \
  --attach stdout \
  --attach stderr \
  --entrypoint "/init" \
  "lscr.io/linuxserver/qbittorrent:latest" \
  
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1003
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 4.6.4-r1-ls332
Build-date: 2024-05-26T13:47:44+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080

The WebUI administrator username is: admin
The WebUI administrator password was not set. A temporary password is provided for this session: pKpp3UYN9
You should set your own password in program preferences.
[ls.io-init] done.
`


following the previous comments I will try to go down the versioens of the container until the webui works again, if since I detect the version in which the failure has occurred I will comment here

**Comment by jzeller2011** [comment] 2024-05-31 17:45
I realize linuxserver.io does not support gluetun integrations, but I've been having this issue (with gluetun included) and I thought i'd share a workaround that worked for me:

- initiate qbittorrent as usual on the default port along with gluetun
- log into the qbit gui and change the webui port to an open port (this will disable your access to the gui temporarily)
- add the new port mapping to gluetun as described in the documentation (matching internal:external ports eg 8080:8080)
- redeploy the qbit container with no port declared, the updated WEBGUI_PORT env variable, and set the network_mode to 'service/container:gluetun'. 
- you can now start a new qbit container on the default port as usual
- repeat as necessary for the number of instances needed

this change persists between restarts/updates. others have had success with compose files with all qbit instances included that list gluetun services last, but I haven't tried that workaround.

**Comment by Copyrighter** [comment] 2024-07-02 22:29
@Arelius-D 
did You able to resolve problem?
I have the same issue. :-(
tried to recreate on QNAP with newer image and from working environment went to ERR_CONNECTION_REFUSED.
locally on docker bash I'm able to use curl http://<IP>:8080 and ping to docker from machine on the same network is working.
only port 8080 is rejected.

**Comment by Arelius-D** [comment] 2024-07-03 03:55
> @Arelius-D 
> 
> did You able to resolve problem?
> 
> I have the same issue. :-(
> 
> tried to recreate on QNAP with newer image and from working environment went to ERR_CONNECTION_REFUSED.
> 
> locally on docker bash I'm able to use curl http://<IP>:8080 and ping to docker from machine on the same network is working.
> 
> only port 8080 is rejected from machine on the same network.
> 
> 
> 
> 
> 
> 

Hey man, yes, couple of updates later it all works again without any changes to my compose files. So this is (was) an issue with this container (qBittorrent) and not at all related to Gluetun.

**Comment by Copyrighter** [comment] 2024-07-03 06:22
@Arelius-D 
thank man!!! :-)
can You tell which tag You are using and is working?
did You done something inside of docker compose? or just left all default 8080->8080, etc. port mappings?

**Comment by Copyrighter** [comment] 2024-07-03 07:03
@Roxedus 
I found a bug in a Docker running on QNAP Docker Station.

WebUI is not accessible after Docker deployment in Bridge mode with Static IP and Default Ports.
Error message: ERR_CONNECTION_REFUSED.
Locally from Docker the port :8080 is accessible both in 127.0.0.1 and <Static IP>.
the ICMP is working from Machine in the same network.
but, no telnet to <Static IP>:8080.

from Docker, no ICMP to DG ... but to Local Machine.

the resolution which works everytime:
ICMP from Docker to Local Machine ( not from Machine to a Docker ).
then ICMP to DG is starting to work.
and :8080 is accessible.

hope it will help to someone.

**Comment by Lukas-Heiligenbrunner** [comment] 2024-07-12 20:37
Qbittorrent doesn't like a port mappings, it expects the same port it has been configured via the env variable. 
-> 8080:8080 works fine for me
8087:8080 i get unauthorized

**Comment by j0nnymoe** [comment] 2024-07-12 21:04
Our documentation does explain how to handle this.

**Comment by hundredfire** [comment] 2024-09-03 23:24
I found that simply adding ``` WebUI\HostHeaderValidation=false ``` to qbitorrent.conf bypassed this issue. What does turning off this setting entails? Wouldn't it fix issues with reverse proxies?

**Comment by drizuid** [comment] 2024-10-30 14:53
I've hidden a lot of posts in this thread as they are offtopic as related to the issue that was opened, which was ostensibly related to the OP not reading how to handle port mapping. It is clearly outlined in the readme. 

Unfortunately, the OP never responded for requests for more information, so I will close this as non-reproducible.

**Closed by drizuid** 2024-10-30 14:53 UTC
Labels: no-issue-activity
