### ISSUE TITLE
Category Folders Do Not Work & Monitor Folder Configs Do Not Save

### ISSUE THREAD

**Issue by BzowK** [linuxserver/docker-qbittorrent#36] opened 2018-12-20 17:59 UTC
Hey Guys - 

I installed the latest build of qBittorrent's Docker container this morning for the first time as I'm considering switching from Deluge which I run on Windows.  Everything is going great except for one thing. 

Seemingly, I cannot save configurations in qBittorrent for Monitoring folders.  Also, when creating Categories with a save path do save, but once the download completes, the completed download is moved to the default download location - not the one for the category it was assigned.

At first I thought it was an issue with the subfolders of mounted volumes as it was saving downloads to the root of the mounted volume (/downloads) -however - when reviewing logs, I saw that it was correctly saving the downloads into the subfolder /downloads/incomplete as configured then moving to the default path once finished.

Below is the string I used to install the container:
> docker run -d \
>   --name=qBittorrent \
>   -v /var/roothome/qbtorrent:/config:z \
>   -v /var/home/user/downloads:/downloads:z \
>   -e PGID=0 -e PUID=0  \
>   -e UMASK_SET=022 \
>   -e WEBUI_PORT=8484 \
>   -e TZ=America/Chicago \
>   -p 6881:6881 \
>   -p 6881:6881/udp \
>   -p 8484:8484 \
>   linuxserver/qbittorrent

_I must add ":z" to end of mounting strings since using Atomic which uses SysLinux and provides full access to the path_

As you can see above, I mounted the host folder "/var/home/user/downloads" to the container's folder "/downloads".  The host folder already contained many other folders as well - each set to 0777 recursively and successfully used by other containers in the past.  I know the paths I am entering exist as well as I can copy/paste them into an SSH session connected to the container to cd to them.

Connecting to the container, I had cd to /downloads where I can view and seemingly have full access to all of the folders I should see including ones like "/downloads/complete/", "/downloads/autoadd/", etc.  I opened qBittorrent's config files in a text editor to see if I could manually make the changes, but do not see where these settings would be/are saved _(in plain text at least.)_

**Monitor Folders**
Below are a examples for how I've tried to configure a couple of the Monitor Folders which do not save.  The paths already exist.
- Source 1: /downloads/autoadd/qbittorrent/complete/
- Other (Save Location) 1: /downloads/complete/
- Source 2: /downloads/autoadd/qbittorrent/isos/
- Other (Save Location) 2: /downloads/isos/

**Category Folders**
Similar to Monitor Folders but more important to me as the Category folders.  I am able to enter paths into them which save and able to assign a category to a torrent.  However, once the torrent completes, it saves into the default download folder instead of the one defined for the category.  Below are exmaples of paths I'm using:
- Default Download Path: /downloads/
- Path for Category "complete": /downloads/complete/
- Path for Category "isos": /downloads/isos/
_I also tried removing the trailing slash which didn't help..._

I examined qbittorrent.log after another failed test where it was not saved in a category's save path.  The only things it mentioned were adding a number of trackers to the torrent, successfully moving the torrent from my incomplete folder to the default download folder, then when it reached the max ratio for seeding.

The container is installed on my host running Atomic Fedora 29.  It is one of over 20 containers which do not have similar issues.

Any suggestions?  Thank You!

**Comment by homerr** [comment] 2019-03-01 09:01
Try running the container as a user, and not as root. The containers aren't designed to run as root and nor should they so add your user to the docker group, get the ID of your user, and recreate the container.

There should be no need for setting chmod's etc on files providing the container has been deployed as designed (not as root)

Sort that and then let's figure out what is going on from there.

**Comment by homerr** [comment] 2019-03-06 13:32
Going to close this as I presume the issue is resolved. If not, please join us in Discord where an available team or community member will be able to assist further.

**Closed by homerr** 2019-03-06 13:32 UTC
Labels: question

**Comment by jef** [comment] 2020-06-07 16:55
I ran into this problem, but was using the the proper `PUID` and `PGID`. I didn't have `UMASK_SET=022` though, because the documentation says that the image will come with it defaulted to that setting. I ran into the problem not being able to save the watch folders until I added that environment variable to the container. Are we sure that it's being set in this case?

**Comment by Germs2004** [comment] 2020-06-28 03:42
for others with this problem: keep in mind, if you are running qBittorrent in a Docker container, the paths you type into the qBittorrent settings are the CONTAINER'S paths, not your Docker host's paths.  If your container's docker-compose file has a volume mount like /home/myname/downloads:/downloads, then you'd need to put /downloads/ in the qBittorrent settings, not /home/myname/downloads/.

**Comment by mpenguin** [comment] 2021-01-10 04:56
Having this same problem on a fresh install of Ubuntu Server 20.04. The relevant part of my docker-compose.yml file:

version: '3'
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - UMASK_SET=022
      - WEBUI_PORT=8090
    volumes:
      - /nas/qbittorrent:/config
      - /nas/downloads:/downloads
      - /nas/incomplete:/incomplete
      - /nas/movies:/movies
      - /nas/shows:/shows
    ports:
      - 65530:65530
      - 65530:65530/udp
      - 8090:8090
    restart: unless-stopped

However, setting a category 'shows' to '/shows' or '/shows/' results in "Cannot write to directory. All /nas/* directories are set to chmod 755 (as per [here](https://forums.plex.tv/t/how-to-mount-media-from-your-nas-shares-on-linux-using-nfs/197947)). How can I get these categories working?

**Comment by Ghilteras** [comment] 2022-04-20 04:53
Same problem as @mpenguin, why is this issue closed?

**Comment by seantcanavan** [comment] 2024-02-20 18:55
For me on unRAID, if I don't run the docker image as 'privileged' aka root then I get an error initializing ip tables.

If I run it as root then I get iptables but I can't re-order columns

**Comment by Ryrynz** [comment] 2024-09-28 04:02
Anything more on this? I can move downloaded files by 'setting location' but categories aren't working to auto move the files to their respective directories.
