### ISSUE TITLE
[BUG] Podman rootles changing mountpoint owner and group

### ISSUE THREAD

**Issue by mkkot** [linuxserver/docker-qbittorrent#256] opened 2023-08-06 17:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When provided compose.yaml is run by user 9003 using podman-compose, it changes ~/.qbittorrent-docker and /data/torrent ownership to 371146:371146 (which is not desired). This is due to some internal UID remapping done by podman when:

1. podman is run as a normal user AND
2. qbittorrent UID/GID is not 0 

I was fighting with PODMAN_USERNS=keep-id and --uidmap options but couldn't make it working. Probably because I can't implement `user:` key for the container as you did some "magic" with PUID and PGID env variables. I wonder if this setup I'm trying to make is supported and if you could shed some light on how this could be achieved.

### Expected Behavior

Rootless podman running qbittorrent container with user and group 9003 doesn't change owner of mount points from 9003:9003 to some podman's internal values.

### Steps To Reproduce

`podman-compose up`. I don't provide the nordvpn configuration but I think it's a typical and obvious setup you already have.

### Environment

```markdown
- OS: Debian Bookworm
podman version 4.3.1
podman-compose version 1.0.6
```

### CPU architecture

arm64

### Docker creation

```bash
qbittorrent:
    image: docker.io/linuxserver/qbittorrent:4.5.4
    network_mode: "service:nordvpn"
    container_name: QbitTorrent-Nord
    depends_on:
      - nordvpn
    environment:
      - WEBUI_PORT=5555
      - TZ=Europe/Berlin
      - PUID=9003
      - PGID=9003
    volumes:
      - "~/.qbittorrent-docker:/config"
      - "/data/torrent:/downloads"
    restart: always
 ```
```


### Container logs

```bash
[qbittorrent] | [migrations] started
[qbittorrent] | [migrations] no migrations found
[qbittorrent] | ───────────────────────────────────────
[qbittorrent] | 
[qbittorrent] |       ██╗     ███████╗██╗ ██████╗ 
[qbittorrent] |       ██║     ██╔════╝██║██╔═══██╗
[qbittorrent] |       ██║     ███████╗██║██║   ██║
[qbittorrent] |       ██║     ╚════██║██║██║   ██║
[qbittorrent] |       ███████╗███████║██║╚██████╔╝
[qbittorrent] |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
[qbittorrent] | 
[qbittorrent] |    Brought to you by linuxserver.io
[qbittorrent] | ───────────────────────────────────────
[qbittorrent] | 
[qbittorrent] | To support LSIO projects visit:
[qbittorrent] | https://www.linuxserver.io/donate/
[qbittorrent] | 
[qbittorrent] | ───────────────────────────────────────
[qbittorrent] | GID/UID
[qbittorrent] | ───────────────────────────────────────
[qbittorrent] | 
[qbittorrent] | User UID:    9003
[qbittorrent] | User GID:    9003
[qbittorrent] | ───────────────────────────────────────
[qbittorrent] | 
[qbittorrent] | [custom-init] No custom files found, skipping...
[qbittorrent] | WebUI will be started shortly after internal preparations. Please wait...
[qbittorrent] | [ls.io-init] done.
```

**Comment by aptalca** [comment] 2023-08-06 17:17
We do not support rootless docker and the issue you're observing is one of many reasons for that.

Closing as it is not a bug.

**Closed by aptalca** 2023-08-06 17:17 UTC

**Comment by mkkot** [comment] 2023-08-06 17:27
Although I don't like the answer, I appreciate it got it so quickly. Anyway, thanks for all the efforts you did to make qbittorrent containerized! I really do appreciate :)

**Comment by thespad** [comment] 2023-08-06 17:29
FWIW we don't chown /data, only /config and /downloads (https://github.com/linuxserver/docker-qbittorrent/blob/master/root/etc/s6-overlay/s6-rc.d/init-qbittorrent-config/run#L12-L21)
